## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID       City Country  Max Temp Current Description      Lat  \
0        5     Avarua      CK     82.45    scattered clouds -21.2078   
1        6       Hilo      US     80.28     overcast clouds  19.7297   
2        9      Vaini      TO     75.36       broken clouds -21.2000   
3       11     Dwarka      IN     81.50           clear sky  22.2394   
4       14  Busselton      AU     64.74     overcast clouds -33.6500   

        Lng                     Hotel Name  
0 -159.7750                   Paradise Inn  
1 -155.0900            Hilo Hawaiian Hotel  
2 -175.2000            Keleti Beach Resort  
3   68.9678  Hotel Narayan Avezika Comfort  
4  115.3333        Observatory Guest House

In [5]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [7]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [23]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"]=="Acapulco")
                                &(vacation_df["Hotel Name"]=="HS Hotsson Smart Acapulco")]
vacation_end = vacation_df.loc[(vacation_df["City"]=="Acapulco")
                                &(vacation_df["Hotel Name"]=="HS Hotsson Smart Acapulco")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"]=="Lazaro Cardenas")
                                &(vacation_df["Hotel Name"]=="HOTEL QUINTA ANTIGUA")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"]=="Miguel Hidalgo")
                                &(vacation_df["Hotel Name"]=="JW Marriott Hotel Mexico City")] 
vacation_stop3 = vacation_df.loc[(vacation_df["City"]=="Tamiahua")
                                &(vacation_df["Hotel Name"]=="Mission Of The Sun Hotel")]

In [24]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = pd.DataFrame(vacation_start[["Lat", "Lng"]]).to_numpy()
end =  pd.DataFrame(vacation_end[["Lat", "Lng"]]).to_numpy()
stop1 = pd.DataFrame(vacation_stop1[["Lat", "Lng"]]).to_numpy()
stop2 = pd.DataFrame(vacation_stop2[["Lat", "Lng"]]).to_numpy()
stop3 = pd.DataFrame(vacation_stop3[["Lat", "Lng"]]).to_numpy()
start, end, stop1, stop2, stop3

(array([[ 16.8634, -99.8901]]),
 array([[ 16.8634, -99.8901]]),
 array([[  17.9583, -102.2   ]]),
 array([[ 19.4225, -99.2028]]),
 array([[ 21.2667, -97.45  ]]))

In [25]:
start=(16.8634, -99.8901)
end=(16.8634, -99.8901)
stop1=(17.9583, -102.2)
stop2=(19.4225, -99.202)
stop3=(21.2667, -97.45)

In [26]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
itinerary_trip_plan = gmaps.directions_layer(start,end, 
                                             waypoints=[stop1,stop2,stop3],
                                             travel_mode="DRIVING")
fig.add_layer(itinerary_trip_plan)
fig

Figure(layout=FigureLayout(height='420px'))

In [27]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID             City Country  Max Temp Current Description      Lat  \
0      373         Acapulco      MX     87.62               smoke  16.8634   
1      684  Lazaro Cardenas      MX     83.91       broken clouds  17.9583   
2      317   Miguel Hidalgo      MX     80.58    scattered clouds  19.4225   
3       94         Tamiahua      MX     85.23           clear sky  21.2667   

        Lng                     Hotel Name  
0  -99.8901      HS Hotsson Smart Acapulco  
1 -102.2000           HOTEL QUINTA ANTIGUA  
2  -99.2028  JW Marriott Hotel Mexico City  
3  -97.4500       Mission Of The Sun Hotel

In [32]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [33]:
# 11a. Add a marker layer for each city to the map.
itinerary_locations = itinerary_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(16.8634, -99.8901), zoom_level=5)
marker_layer = gmaps.marker_layer(itinerary_locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))